### ISSUE TITLE
无线网无法使用

### ISSUE THREAD

**Issue by jinweizhiyuan** [fengwenhua/dell-7559-hackintosh#10]
安装完黑苹果后，屏幕项部没有无线网图标，支控制台也找不到添加wifi的地方

**Comment by fengwenhua** [comment]
你用的是和我一样的usb无线网卡?

**Comment by jinweizhiyuan** [comment]
> 你用的是和我一样的usb无线网卡?
我用的是intel自带的无线

**Comment by fengwenhua** [comment]
兄弟~~要是你能搞到笔记本自带的网卡驱动, 记得发出来, 让大家一起用~~~

**Comment by jinweizhiyuan** [comment]
> 
> 
> 兄弟~~要是你能搞到笔记本自带的网卡驱动, 记得发出来, 让大家一起用~~~

^^没有那个能力
