### ISSUE TITLE
修复蓝牙中，文件显示只读

### ISSUE THREAD

**Issue by player41** [fengwenhua/dell-7559-hackintosh#11]
您好，我更新了一下驱动 升级到了10.15。然后尝试修复蓝牙，但那个info.plist是只读的，我修改不了，替换也不行。请问你在编辑中有遇到过这种问题吗？请问你是怎么解决的？

**Comment by fengwenhua** [comment]
10.15需要解锁S/L/E权限, 方法如下:

```
sudo su
sudo mount -uw /
killall Finder
```

运行完上面的命令再替换即可
