### ISSUE TITLE
安装完成后没有音频设备，无法调节音量

### ISSUE THREAD

**Issue by comack** [fengwenhua/dell-7559-hackintosh#12]
![QQ20191105-112327](https://user-images.githubusercontent.com/24933537/68176178-be1dbd80-ffbe-11e9-93bd-4cda7efdd135.png)
请问一下，我重做了很多遍dsdt文件，一直都找不到音频设备

**Comment by fengwenhua** [comment]
尝试升级Lilu, AppleALC, WhateverGreen 到最新版本试试?

**Comment by comack** [comment]
谢谢，替换了一下你的config.plist文件就好了，可以用了。
