### ISSUE TITLE
咨询：10.14.4理论上可以直接升级15.1么

### ISSUE THREAD

**Issue by sunshinenny** [fengwenhua/dell-7559-hackintosh#13]
## 我的情况：
1. 10.14.4
2. 自行添加了 dw1560网卡「可正常驱动」

想试试胆肥点直接升级15.1😂

不清楚行不行，烦请老哥指点

**Comment by fengwenhua** [comment]
1. 先删掉`/System/Library/Extensions/`下的`AppleIntelLpssI2C.kext` 和 `AppleIntelLpssI2CController.kext`
2. 升级clover到最新
3. 升级`whatevergreen`, `lilu`, `AppleALC`为最新
4. 拔了wifi网卡
5. 直接升级
6. 赌一把~

**Comment by sunshinenny** [comment]
> * 先删掉`/System/Library/Extensions/`下的`AppleIntelLpssI2C.kext` 和 `AppleIntelLpssI2CController.kext`
> * 升级clover到最新
> * 升级`whatevergreen`, `lilu`, `AppleALC`为最新
> * 拔了wifi网卡
> * 直接升级
> * 赌一把~

好的😂 感觉可行～

**Comment by sunshinenny** [comment]
### 谢谢作者大大的帮助
等了超长时间终于敢尝试一下
最后按照方法成功上到了15.1

###顺便再问问别的问题……
15.1的Wi-Fi和蓝牙都挂了😂

### 现在情况是
- 想想1560好像15.1支持没这么好，干脆就和作者大大买个一样的1820a吧…
- 1820a的Wi-Fi驱动特慢… 开机后几分钟才可以连上网(ｰ ｰ;)
- 蓝牙直接挂掉…
    - 「都是按照教程做的[捂脸]」
    - 「我自己改过/Library/Extensions/下的驱动… 现在傻眼了… 因为自己忘记了上次改了啥😂…不知道您能不能发一下您的」
    - 我也不知道驱动不了蓝牙会不会和 LE 有关系…

**Comment by fengwenhua** [comment]
改了`/Library/Extensions/`这些驱动, 直接重装是最快的...

我的1820a的驱动安装都是直接照着黑国小兵大佬的教程来的, 稳如狗, 没出现过卡的情况, 如果你照着同样的教程操作完了, 还是出现了问题, 只有一个原因, 就是你买错了1820a网卡, 我的网卡如下: 

![image](https://user-images.githubusercontent.com/26518808/70303142-cf661e00-1839-11ea-9d3d-a8ada7a3768c.png)

所以, 自己认真看看, 是不是同一张网卡? 如果是同一型号的, 是不是你的网卡是出现故障了?

**Comment by sunshinenny** [comment]
> 来源小兵教程贴[DW1820A设备信息整理](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)

Part Number | Manufacturer | Module | WLAN | BT 4.1
-- | -- | -- | -- | --
CN-0VW3T3 | Dell Wireless 1820A 802.11ac | BCM94350ZAE_2 | 1028:0021 | [0a5c:6412]
CN-0VW3T3 | Dell Wireless 1820A 802.11ac | BCM94356ZEPA50DX_2 | 1028:0021 | [0a5c:6412]
CN-08PKF4 | Dell Wireless 1820A 802.11ac | BCM94356ZEPA50DX_2 | 1028:0023 | [0a5c:6412]
****
您的网卡看编号应该是前两者之一，我的是粘出来的第三个… 逻辑上判断蓝牙应该是一样的😂应该可以用的呀:-D

可能就是我买错了或者买的网卡有点问题吧……:(

****
先凑活用一段时间，以后再看看能不能再改进改进（或者哪天项目做完了直接整个重装快乐似神仙😄）

谢谢您的帮助🎉

**Comment by fengwenhua** [comment]
这我就帮不了你了, 因为我没有用过`CN-08PKF4`, 保重!! 等你啥时候解决了, 记得回来这里说一声!!!

**Comment by sunshinenny** [comment]
Yes sir😄

祝生活愉快

**Comment by hostsdreamer** [comment]
> Yes sir😄 祝生活愉快
> […](#)
> 在 2019年12月6日，15:42，冯文华 ***@***.***> 写道： ﻿ 这我就帮不了你了, 因为我没有用过CN-08PKF4, 保重!! 等你啥时候解决了, 记得回来这里说一声!!! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你的无线网卡有没有换啊。我好像也买的这个

**Comment by sunshinenny** [comment]
没换 还是老毛病…
Wi-Fi开机后读取巨慢（几分钟后才可以连上网）
蓝牙不可用
