### ISSUE TITLE
卡在了  进入clover之后的安装界面

### ISSUE THREAD

**Issue by royccg** [fengwenhua/dell-7559-hackintosh#14]
我的电脑也是I7的，bios版本是 1.3.1.
1.我安装10.14.5的系统，进入clover之后，卡在了 Start InitDeviceTree，
前面的代码也出现 Block device not supportSuccess。能帮我看下吗？谢谢
![photo_2019-11-22_09-25-44](https://user-images.githubusercontent.com/44716144/69390400-16b4c080-0d0a-11ea-9769-e5ca05704f50.jpg)

2.还有我想直接安装macOS10.15时  也是卡在进入clover之后，点击了  安装，之后就黑屏，屏幕中间有个白底线（一个空格占位 _ ），这有解决办法吗？

3. 再有，我想问下，黑果小兵的 qq交流群，有人进去吗？那个 进入的验证问题，blog的域名是多少，有人知道答案吗？我输入了blog.daliansky.net  daliansky.net  daliansky，这些都不对啊？真的是尴尬。

最后，还是跪谢。

**Comment by fengwenhua** [comment]
1. 我没遇到过你这个问题
2. 你用的系统是黑果小兵的系统吗? 验证过md5了吗?
3. **我本人只用到了小兵的`10.14.5`**, 之后的系统, 我都装不了, 我也不知道是啥原因, 我都是直接装`10.14.5`, 然后装完直接升级的
4. 你用之前改了config了没? 千万别硬套我的clover啊~~
5. bios正确设置了没?
6. 如果以上都不能解决, 那我也没办法了, 因为我真的没遇到过这个问题(也可能是我忘了)
7. 小兵的交流群是啥我也不知道... ...

**Comment by royccg** [comment]
你好，大佬。我现在能安装了  但是到DSDt文件制作时，我不能把 iasl文件写入  /usr/bin 显示iasl是只读文件,这个能解决吗，谢谢



            
            
                
                    
                            
                                
                            
                            
                                1804130207
                            
                    
                        
                            
                                    邮箱：1804130207@njtech.edu.cn
                            
                        
                
            
        


            在2019年11月22日 19:30，冯文华 写道： 
我没遇到过你这个问题
你用的系统是黑果小兵的系统吗? 验证过md5了吗?
我本人只用到了小兵的10.14.5, 之后的系统, 我都装不了, 我也不知道是啥原因, 我都是直接装10.14.5, 然后装完直接升级的
你用之前改了config了没? 千万别硬套我的clover啊~~
bios正确设置了没?
如果以上都不能解决, 那我也没办法了, 因为我真的没遇到过这个问题(也可能是我忘了)
小兵的交流群是啥我也不知道... ...


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fengwenhua/dell-7559-hackintosh/issues/14?email_source=notifications\u0026email_token=AKVFA4G456FO6HGFTNSDHS3QU672BA5CNFSM4JQKNCQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE5MHDQ#issuecomment-557499278",
"url": "https://github.com/fengwenhua/dell-7559-hackintosh/issues/14?email_source=notifications\u0026email_token=AKVFA4G456FO6HGFTNSDHS3QU672BA5CNFSM4JQKNCQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE5MHDQ#issuecomment-557499278",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by royccg** [comment]
你好，大佬。我现在能安装了  
1.但是到DSDt文件制作时，我不能把 iasl文件写入  /usr/bin 显示iasl是只读文件,这个能解决吗，谢谢。
2. 那个 GTX960M是不是没办法装驱动啊。

**Comment by fengwenhua** [comment]
1. 对于`iasl`, 给它执行权限就行, 如下:

```shell
chmod +x iasl
```

2. 我不会装960M的驱动, 我都是屏蔽掉它的...只用核显.

**Comment by royccg** [comment]
大大，我想询问下，你的触摸盘的手势，支持吗？
我现在的 在10.15.2上，触摸盘的移动鼠标和点击都正常，但是手势感觉不支持，能问下你那边的情况，谢谢。

**Comment by fengwenhua** [comment]
> 大大，我想询问下，你的触摸盘的手势，支持吗？
> 我现在的 在10.15.2上，触摸盘的移动鼠标和点击都正常，但是手势感觉不支持，能问下你那边的情况，谢谢。

手势没搞, 等我做完毕设再说吧~~你也可以去搞搞: http://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/

**Comment by royccg** [comment]
> > 大大，我想询问下，你的触摸盘的手势，支持吗？
> > 我现在的 在10.15.2上，触摸盘的移动鼠标和点击都正常，但是手势感觉不支持，能问下你那边的情况，谢谢。
> 
> 手势没搞, 等我做完毕设再说吧~~你也可以去搞搞: http://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/

之前，有次装机，不知道怎么弄的，可以使用触摸盘的手势，可是后来重装之后，现在就不行了。
感觉笔记本上没有手势，在macos上 回到桌面，切换程序等，还是比较麻烦。大神，你有好的方式吗？

**Comment by fengwenhua** [comment]
我记得在10.13.6的时候, 触摸板的手势是可以用的, 后来不行了, 我现在的话, 直接改系统快捷键的, 
`系统偏好设置`->`键盘`->`快捷键`->`调度中心`:

![image](https://user-images.githubusercontent.com/26518808/72705477-832b2f00-3b96-11ea-9edb-fb8f42bb39b4.png)

改好之后, `Ctrl+A`和`Ctrl+D`切换桌面, `Ctrl+D`是调度中心, `Windows+D`是桌面! 我个人感觉比触摸板快多了!!

**Comment by royccg** [comment]
1、大神，你换了 无线网卡，感觉用的怎么样啊
2、我听说1820A的网卡不是非常好，推荐BCM94360(DW1830)、BCM94352(DW1560A)的网卡，但是有些接口不是m.2的，不知道您有没有看过这些网卡

**Comment by fengwenhua** [comment]
感觉很稳呀, 完全正常使用呀, 具体的话, 只要买到对的就行, 去 https://github.com/fengwenhua/dell-7559-hackintosh/issues/13 看看, 我拍过我买的那张卡的照片
其他的没有看过~~
