### ISSUE TITLE
老大我是i5的启动后有线网也连接不上  设备里面提示没有有用的PCI以太网卡

### ISSUE THREAD

**Issue by hostsdreamer** [fengwenhua/dell-7559-hackintosh#17]
老大我是i5的安装好后有线网也连接不上  设备里面提示没有有用的PCI以太网卡 PPPOE无法拨号 然后网线连接路由器也不能上网 这个怎么办 求指教  困扰2天了 谢谢

**Comment by hostsdreamer** [comment]
好吧，我解决了 老大 我感谢你的教程

**Comment by fengwenhua** [comment]
额, 没搞懂你的问题, 总之没问题就行!
