### ISSUE TITLE
BlockSize：512Legacy问题

### ISSUE THREAD

**Issue by NieHang** [fengwenhua/dell-7559-hackintosh#2]
![](https://i.loli.net/2019/04/16/5cb56b1080233.jpg)
我是i5的，bios版本是1.0.1
想问下你有没有出现过这样的问题

**Comment by fengwenhua** [comment]
抱歉， 我没有遇到过这个问题，你是用什么软件刻录启动u盘的？？
另外， 附上tonymac上的解决方案： https://www.tonymacx86.com/threads/blocksize-512legacyapfscontainerscan-block-device-not-supportedsuccess.270417/

**Comment by NieHang** [comment]
> 抱歉， 我没有遇到过这个问题，你是用什么软件刻录启动u盘的？？
> 另外， 附上tonymac上的解决方案： https://www.tonymacx86.com/threads/blocksize-512legacyapfscontainerscan-block-device-not-supportedsuccess.270417/

我是用transmac刻录的。
这个解决方案我之前用过了，不好用。
非常感谢你的解答。

**Comment by player41** [comment]
我是替换成镜像自带的drivers64UEFI和cloverx64.efi 然后就可以了 不过这两条出现后可以等下 说不定能开

**Comment by NieHang** [comment]
> 我是替换成镜像自带的drivers64UEFI和cloverx64.efi 然后就可以了 不过这两条出现后可以等下 说不定能开

已经解决了，忘了咋解决的了(手动滑稽)
