### ISSUE TITLE
升级到10.15.4 缺少 colver文件

### ISSUE THREAD

**Issue by royccg** [fengwenhua/dell-7559-hackintosh#22]
您好，您在更新10.15.4时的 
```
BOOTX64.efi替换EFI/BOOT文件夹中的同名文件。
CLOVERX64.efi替换EFI/CLOVER文件夹中的同名文件。
```
这两个文件 能给个下载链接吗？
我没有远景的账号，所以下载不了啊，尴尬

**Comment by royccg** [comment]
或者 给个 远景的邀请吗  我也是不胜感激啊

**Comment by fengwenhua** [comment]
[clover5107.zip](https://github.com/fengwenhua/dell-7559-hackintosh/files/4386344/clover5107.zip)

**Comment by royccg** [comment]
谢谢 大佬
