### ISSUE TITLE
关机变重启，睡眠唤不醒

### ISSUE THREAD

**Issue by NieHang** [fengwenhua/dell-7559-hackintosh#3]
你好，请问你有遇到过这样的问题吗？

**Comment by fengwenhua** [comment]
你好, 我没有遇到过这个问题, 你是按照我的教程来打驱动的吗?是在打驱动之前就这样, 还是打完驱动后出现这些问题?

**Comment by NieHang** [comment]
打完驱动之后出现的，不过我现在用不惯黑苹果，用回windows了，非常感谢你的帮助！
