### ISSUE TITLE
使用您的方法安装启动时提示Start Start osName end osName init deviceTree的错误

### ISSUE THREAD

**Issue by sunshinenny** [fengwenhua/dell-7559-hackintosh#5]
## 硬件配置
- 除了非双张4G内存之外，和您的配置无出入
- BIOS特地刷成了1.2.8

## 修改BIOS时候遇到的问题
 - 恢复BIOS默认设置
 - **AHCI mode 选择 SATA**
……………………
没有第二步这一个选项，找不到属于哪个标签卡中。。。

## 启动安装时遇到的问题
第一次使用教程中的修改文件名的方法，修改好了CLOVER，启动时报错，错误类型如标题
第二次直接删除CLOVER，换成“最终CLOVER”，报错同上。

> 查其他教程他们解决办法是「拔掉所有的外接设备，包括AC交流充电，在开机时出现DELL徽标的时候插入U盘，再启动UEFI形式的CLOVER引导」
以上方式均尝试过了，无果 (￣O￣;)

启动方式也尝试过UEFI和Legacy，均报错如题。。。
*****
头大如斗，冒昧请教您一下。
感谢您如此完善的教程。

**Comment by sunshinenny** [comment]
### 参考链接
[【安装教程】Dell 7559 安装10.14GM（i5+UEFI）](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1794485&extra=page%3D1&page=1&mobile=yes)
[[Guide] Dell Inspiron 15 7559 Sierra/High Sierra/MOJAVE Install](https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7559-sierra-high-sierra-install.201576/)

**Comment by fengwenhua** [comment]
你好, 感谢你认真阅读了我的教程! 

首先, 很抱歉, 我没有遇到过这个问题, 所以我没有正解. 不过, 我会从以下几个方面考虑:

1. **AHCI mode** 在Bios里面是 **SATA Operation** , 值是`AHCI`即可. 然后检查其他bios设置是否与教程中的一致
2. 正常来说, 只要是`HD530`的config.plist就应该可以安装成功, 所以, 下载的系统中有两个`HD530`的config文件, 你可以尝试一下另一个
3. 检测下载的系统md5值是否与官网一致
4. 有三个USB口, 三个都试试
5. 换个u盘试试

> 如果到了这一步还不行的话, 我怀疑你是不是假的dell 7559... ...

6. 还不行的话, 去远景找另外的大佬打包的系统, 用其他的系统试试
7. 都不行, 认真百度谷歌系统安装失败的提示, 看看有没有解决方案吧!!!

最后, 保重~~~~

**Comment by sunshinenny** [comment]
感谢您的解答

最近比较忙，有空就去重新尝试👌🌟😊

**Comment by sunshinenny** [comment]
经过千辛万苦，终于完成了安装
在引导盘的时候将内置电源的排线拔掉就可以了，安装完成之后再安装回去一点影响都没有
ps：想求一个 IOBluetoothFamily.kext 文件。。。在倒腾的时候。。。一不留神就不见了。。。再也找不到了。。。
邮箱为sunshinenny@icloud.com

麻烦您了 万分感谢🙏

**Comment by fengwenhua** [comment]
很高兴你竟然用这么骚的操作完整的安装~~~~

顺便说一声, 前几天10.14.5 出来的时候, 我已经完成了升级, 升级完后, 只需要修复蓝牙驱动就行了, 不知道你敢不敢更一波~~~哈哈哈!!!

附上**10.14.5**的IOBluetoothFamily.kext, 不知道你能不能用.

[IOBluetoothFamily.kext.zip](https://github.com/fengwenhua/dell-7559-hackintosh/files/3217569/IOBluetoothFamily.kext.zip)

**Comment by sunshinenny** [comment]
嘿嘿
感谢您的驱动，目前系统一切正常啦。
真的真的好有成就感

感谢您的热枕和优秀的教程。

再次拜谢😄

**Comment by zjw1111** [comment]
你好！
我把电池排线拔了之后可以正常安装/运行系统，驱动也都装好了。但是把电池插上之后系统依旧不能运行，启动时卡在“init deviceTree”。
请问你是怎么解决的？

**Comment by HakureiKion** [comment]
在BIOS中设置Battery Charge Configuration为Standard即可。BIOS默认是Adaptive，在这一模式下会卡InitDeviceTree。
