### ISSUE TITLE
戴尔7559安装完成后 显示不了电量 

### ISSUE THREAD

**Issue by comack** [fengwenhua/dell-7559-hackintosh#6]
我是i7版本的  系统报告里也没有电池信息，请问你知道如何解决吗

**Comment by fengwenhua** [comment]
![image](https://user-images.githubusercontent.com/26518808/59351149-4b325280-8d50-11e9-831f-6fe8e5f50733.png)

这个补丁就是修复电量显示的啊~~~, 至于你为啥不行, 我也不太清楚!!!

**Comment by comack** [comment]
谢谢，现在可以了，可能是当时漏掉了。。。
