### ISSUE TITLE
请问一下，现在我i5版本安装完10.14.5以后，快捷键小太阳怎么不能用？

### ISSUE THREAD

**Issue by whl2638916** [fengwenhua/dell-7559-hackintosh#7]
RT，好像我cpu变频也只有4档。。。。不知道小太阳现在能用不TAT

**Comment by fengwenhua** [comment]
这个我也帮你不了.... ...

**Comment by jinweizhiyuan** [comment]
我的也是，调亮和调暗都不管用

**Comment by fengwenhua** [comment]
去https://pqrs.org/osx/karabiner/ 下载安装一个karabiner, 然后试试Fn+F1/F2有没有效果?

**Comment by jinweizhiyuan** [comment]
> 去https://pqrs.org/osx/karabiner/ 下载安装一个karabiner, 然后试试Fn+F1/F2有没有效果?

我用的是clover里边的驱动，没有单独下载，按Fn+PtrScr可以调高亮度，没法调暗

**Comment by fengwenhua** [comment]
我装完系统也是无法调节亮度, 直到我装了`karabiner`, 然后就可以用`Fn+F1/F2`来调节亮度了...
