### ISSUE TITLE
耳机暴音修复出现错误，并且导致睿频和睡眠都出现问题了。

### ISSUE THREAD

**Issue by huguangwen** [fengwenhua/dell-7559-hackintosh#9]
运行耳机修复command的时候出现如下错误，请问应该怎么修复。

![屏幕快照 2019-09-12 下午10 10 44](https://user-images.githubusercontent.com/32874705/64903881-12b75300-d676-11e9-903a-8162d04eb82b.png)

**Comment by fengwenhua** [comment]
这是在重建缓存, 没有问题啊~~

**Comment by huguangwen** [comment]
嘿嘿，更新catalina 了没

冯文华 <notifications@github.com> 于 2019年10月10日周四 03:59写道：
